### ISSUE TITLE
How can I compile Axml back to binary?

### ISSUE THREAD

**Issue by isMeiying** [rednaga/axmlprinter#11]
How to restore to xml after toXml() can read xml

**Comment by strazzere** [comment]
You should look at the tests -- specifically;

`testWriteInsertedApplicationAttribute()`

https://github.com/rednaga/axmlprinter/blob/master/src/test/java/android/content/res/TestAXMLResource.java#L120

You're looking for the `write()` function.

**Comment by isMeiying** [comment]
ok, thanks.

But I tried toxml, some places are missing, how can I solve it?
![image](https://user-images.githubusercontent.com/13428030/61236923-c9c54a00-a76b-11e9-8177-efab5fb7d8d8.png)

**Comment by isMeiying** [comment]
![image](https://user-images.githubusercontent.com/13428030/61236956-e19cce00-a76b-11e9-8754-9de26d46b123.png)
It is missing a lot

**Comment by strazzere** [comment]
Understood - looks like there are bugs, which is pretty known. I suggest you try to identify what the issues are and create bugs for them?

Though it would appear you're doing the correct operation.

**Comment by isMeiying** [comment]
Oh, I am very sorry that I don't know what caused the problem. I use apktool or this https://github.com/fourbrother/AXMLEditor/ to resolve this problem, but unfortunately they are not perfect.

**Comment by strazzere** [comment]
Can't speak for that repo, however you can try using APKTool and see if they have the bugs fixed.

Per whats causing the issue, if you can take the screen shots you have, create a new issue and upload an example AndroidManifest.xml which causes these issues, while noting what your expected output would be - this would be enough to create a test case and fix the issues.

**Comment by isMeiying** [comment]
Apktool no problem, But it can't compile res

this is my AndroidManifest:
[AndroidManifest.zip](https://github.com/rednaga/axmlprinter/files/3393608/AndroidManifest.zip)

**Comment by isMeiying** [comment]
In the right case they should be like this:

![image](https://user-images.githubusercontent.com/13428030/61239462-84a41680-a771-11e9-855f-5a6a63bab93e.png)
