### ISSUE TITLE
Output format

### ISSUE THREAD

**Issue by xqinghu** [rednaga/axmlprinter#3]
![i](https://cloud.githubusercontent.com/assets/3013540/14104132/0a66f540-f5d6-11e5-9dc0-d9ec50ec6e84.png)

**Comment by CalebFenton** [comment]
What's the problem? Also, can you post a link to the file (if there is actually a problem)?

**Comment by strazzere** [comment]
I think he's reporting that the xmlns:android tag is outside of the manifest tag (technically) - the original AXMLPrinter would drop it into the manifest tag like so;
`<?xml version="1.0" encoding="utf-8"?>
<manifest
	xmlns:android="http://schemas.android.com/apk/res/android"
	android:versionCode="1066"
	android:versionName="2.2.1"
	package="com.quora.android"
	platformBuildVersionCode="19"
	platformBuildVersionName="4.4.2-1456859"
	>
`

However it did this with some really dirty state tracking code... I'll look into it again, but I remember thinking it was just a hack and gross - and less important. Might be important if people are using this in conjunction with apktool or something?

@xqinghu is this causing a breakage anywhere else? Or is it just not pretty :)

**Comment by xqinghu** [comment]
Is it just not pretty :)
use:  java -jar axmlprinter-0.1.5.jar 1.txt

[1.txt](https://github.com/rednaga/axmlprinter/files/195243/1.txt)

**Comment by strazzere** [comment]
Hah, ok. I'll keep this open, though you're more than welcome to send a pull request fixing it too :)

**Comment by anantshri** [comment]
just encountered this. Was using this code with MobSF trying to see if this new axmlparser can replace the old one. Looks like this code is not yet production ready. This one line flip is making life harder for other automated tools.

**Comment by strazzere** [comment]
@anantshri I'm not sure what you're referencing - though you're welcome to submit a fix if you'd like.

This as absolutely zero priority to me as it fundimentally works and the output doesn't mean much to me. It creates objects perfectly fine for all the automation I've used.

If you're integrating with this tool via swallowing the printfs - I'd like to say that the integration is not correct. However I'm not exactly sure what you're doing - so don't take that as an offensive comment please :)

**Comment by anantshri** [comment]
@strazzere none taken. Let me detail out what i was trying and you could be the best one to suggest if that will work.

So MobSF @ https://github.com/ajinabraham/Mobile-Security-Framework-MobSF uses AXML2Printer internally to perform some action. https://github.com/MobSF/Mobile-Security-Framework-MobSF/blob/f42b8321507c540b341832e99b93ccee775b49bd/StaticAnalyzer/views/android/manifest_analysis.py#L1239 is where its taking AXML2Printer and getting the Manifest and reading it via printf output.

Now I was looking at integrating MobSF within AndroidTamer tool set and realized AXML2Printer is something which is neither actively maintained nor easy to get from official source. Hence this project came into light. it appeared that this could be a drop in replacement. So i changed the binary path as it allows users to use preinstalled tools. As it stands the output of this program (printfs) are out of alignment (only line 3 and 2) and hence the output is not directly usable as a valid XML source.

So this is the scenario which led me to this particular issue and it seems this was long known so was just poking to see what's going on in this.

I don't think i am competent enough to send a pull but if i do find a way to get things going i will update it here.

Also as you suggested printf's are not best way, do you have any sample code which i can refer for best use case scenario's.
